[package]
name = "my_macro_consumer"
version = "0.1.0"
authors = ["“Wison Ye” <wisonye@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust_lang.org/cargo/reference/manifest.html

[dependencies]
my_macro_lib={ path = "../my_macro_lib", version = "0.1.0" }
